### ISSUE TITLE
tracer generates wrong global memory write addresses

### ISSUE THREAD

**Issue by allencho1222** [accel-sim/accel-sim-framework#22] opened 2020-11-03 17:58 UTC
I am using current release version of accelsim framework (nvbit tracer 1.5v)

I used tracer for rodinia-3.1 bfs with input data 'graph1MW'

The tracer runs over 2080 Ti.

cudaMalloc and cudaMempcy generated from tracers look like this:

cudaMalloc,0x00007fb50a800000,8000000
MemcpyHtoD,0x00007fb50a800000,8000000
cudaMalloc,0x00007fb50e000000,23999880
MemcpyHtoD,0x00007fb50e000000,23999880
cudaMalloc,0x00007fb50a700000,1000000
MemcpyHtoD,0x00007fb50a700000,1000000
cudaMalloc,0x00007fb50b000000,1000000
MemcpyHtoD,0x00007fb50b000000,1000000
cudaMalloc,0x00007fb50b0f4400,1000000
MemcpyHtoD,0x00007fb50b0f4400,1000000
cudaMalloc,0x00007fb50b200000,4000000
MemcpyHtoD,0x00007fb50b200000,4000000
cudaMalloc,0x00007fb50a7f4400,1
MemcpyHtoD,0x00007fb50a7f4400,1
kernel-1.traceg
kernel-2.traceg
MemcpyHtoD,0x00007fb50a7f4400,1
kernel-3.traceg
kernel-4.traceg
MemcpyHtoD,0x00007fb50a7f4400,1
kernel-5.traceg
kernel-6.traceg
MemcpyHtoD,0x00007fb50a7f4400,1
kernel-7.traceg
kernel-8.traceg
MemcpyHtoD,0x00007fb50a7f4400,1
kernel-9.traceg
kernel-10.traceg
MemcpyHtoD,0x00007fb50a7f4400,1
kernel-11.traceg
kernel-12.traceg
MemcpyHtoD,0x00007fb50a7f4400,1
kernel-13.traceg
kernel-14.traceg
MemcpyHtoD,0x00007fb50a7f4400,1
kernel-15.traceg
kernel-16.traceg
MemcpyHtoD,0x00007fb50a7f4400,1
kernel-17.traceg
kernel-18.traceg
MemcpyHtoD,0x00007fb50a7f4400,1
kernel-19.traceg
kernel-20.traceg
MemcpyHtoD,0x00007fb50a7f4400,1
kernel-21.traceg
kernel-22.traceg
MemcpyHtoD,0x00007fb50a7f4400,1
kernel-23.traceg
kernel-24.traceg
cudaFree,0x00007fb50a800000
cudaFree,0x00007fb50e000000
cudaFree,0x00007fb50a700000
cudaFree,0x00007fb50b000000
cudaFree,0x00007fb50b0f4400
cudaFree,0x00007fb50b200000

However, in kernel 5, wrong global memory write address is shown:

0290 00000000 0 STG.E.U8.SYS 2 R12 R0 1 2 0x4db0d
0290 00004000 0 STG.E.U8.SYS 2 R12 R0 1 2 0x4db0d 140415550357506 
0290 00000000 0 STG.E.U8.SYS 2 R12 R0 1 2 0x4db0d
0290 00000000 0 STG.E.U8.SYS 2 R12 R0 1 2 0x4db0d
0290 00000000 0 STG.E.U8.SYS 2 R12 R0 1 2 0x4db0d
0290 00000000 0 STG.E.U8.SYS 2 R12 R0 1 2 0x4db0d 

I cannot understand why the tracer generates these memory addresses.

I couldn't figure out the address 0x4db0d which accesses global memory.

0x4db0d does not correspond to the address ranges from cudaMalloc.

Even the thread mask bits are zero except the second instructions shown above.

Is this bug?

**Comment by mkhairy** [comment] 2020-11-03 18:18
The addresses are saved in base+delta compression format. 
The compression code can be found here:
https://github.com/accel-sim/accel-sim-framework/blob/4c2bf09a79d6b57bb10fe1898700930a5dd5531f/util/tracer_nvbit/tracer_tool/tracer_tool.cu#L484

So, 0x4db0d (hexa) is the base, and 140415550357506 is delta in decimal (0x7FB50B000002 in hexa).

So the final address of the active thread = 0x4db0d + 0x7FB50B000002 (hexa) = 0x7FB50B04DB0F (hexa) which maps to one of the cudamalloc addresses.

You are right that the compression base address needs to be equal to cudamalloc address, but this how our compression ends up with. I may need to double-check later why this difference has happened. However, for now, I think this is not a bug as the addresses generated are within the correct range.

**Comment by allencho1222** [comment] 2020-11-03 18:35
@mkhairy Thank you for detailed answer. But what about other instructions that do not have delta address? Even these instructions have no thread mask bits turned on.

**Comment by mkhairy** [comment] 2020-11-03 18:50
yeah, these instructions do not have any active thread, so they won't generate any addresses and will be skipped at the pipeline. We just report them for accurate instructions count with the hardware, as the hardware report these in the total instruction count.

**Comment by mkhairy** [comment] 2020-11-03 19:31
But, wait, I double-check the code again, this is a bug. If you only have one active thread, then the base address only should be reported and nothing should be reported in the other cases.

**Comment by mkhairy** [comment] 2020-11-03 19:32
can you please replace this line in the tracer:
https://github.com/accel-sim/accel-sim-framework/blob/4c2bf09a79d6b57bb10fe1898700930a5dd5531f/util/tracer_nvbit/tracer_tool/tracer_tool.cu#L549

from

std::bitset<32> mask(ma->active_mask);

to

std::bitset<32> mask(ma->active_mask & ma->predicate_mask));

and see how the output will look like.

**Comment by allencho1222** [comment] 2020-11-04 02:43
@mkhairy Thank you for your help. It works correctly now (the base address is correctly printed). By the way, trace parser uses 0x4db0d as the memory address of the first active thread, while the second thread uses correct address (But only one active thread exist in my example). Does this also happen when the tracer is fixed? It seems that it will not happen any more because the base address calculation was incorrect so that the base address was represented as 0x4db0d.

https://github.com/accel-sim/accel-sim-framework/blob/4c2bf09a79d6b57bb10fe1898700930a5dd5531f/gpu-simulator/trace-parser/trace_parser.cc#L111

**Comment by mkhairy** [comment] 2020-11-04 18:06
yeah, my explanation that I mentioned earlier was incorrect. The first address is used as the memory address for the first active thread then it used as a base address for the next one and so on. As shown below:
https://github.com/accel-sim/accel-sim-framework/blob/4c2bf09a79d6b57bb10fe1898700930a5dd5531f/gpu-simulator/trace-parser/trace_parser.cc#L119

Could you please send me the memory traces to see how it looks like now? I just want to take a look at it, so can I safely close this issue.

**Comment by allencho1222** [comment] 2020-11-05 02:55
@mkhairy I sent you an email. Please check and close the issue if it is correct.

**Comment by mkhairy** [comment] 2020-11-05 14:02
ok, good, I got it. can you please create PR for this fix in the dev branch? and I will accept it.
We are also going to regenerate the traces to get the correct addresses and release them.
Note that this bug should only affect irregular divergent workloads, other regular workloads should not be affected by this.
Thanks!

**Closed as completed** 2020-11-06 08:30 UTC
